### ISSUE TITLE
Crashes when names are duplicated in @docs

### ISSUE THREAD

**Issue by alexgig** [panosoft/elm-docs#1]
e.g. `@docs value, value` causes `Generator.makeTableOfContents` to crash.

**Comment by cscalfani** [comment]
After looking at this, we determined it was an issue with duplicates not within the same `@docs` but multiple `@docs`, e.g.

```elm
{-|
@docs value
@docs other
@docs value
}
```
The case given above `@docs value, value` was handled properly.
